import { GoogleGenAI } from "@google/genai";

const PROMPT_MICHELIN = "Transform this dish into a Michelin-star masterpiece. Focus on elegant plating, minimal portions, artistic sauce drizzles, exquisite lighting, and fine dining presentation. Keep the core ingredients but elevate the style.";

const PROMPT_GUIDE = "Create a 4-panel step-by-step preparation guide for this dish as a single image with a 2x2 grid layout. Top-Left (Step 1): Show the empty plate with just the base sauce or puree. Top-Right (Step 2): Show the first layer of ingredients placed carefully. Bottom-Left (Step 3): Show the main protein or element added with some garnish. Bottom-Right (Step 4): The final finished dish exactly as shown in the input image. The style should be photorealistic, instructional, and consistent lighting.";

// Initialize securely from environment
const getAI = () => new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateNanoBananaImage = async (base64Data: string, mimeType: string): Promise<string> => {
  const ai = getAI();
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Data,
            mimeType: mimeType,
          },
        },
        {
          text: PROMPT_MICHELIN,
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1",
      }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  throw new Error("No image generated by Nano Banana");
};

export const generateNanoBananaProImage = async (base64Data: string, mimeType: string): Promise<string> => {
  // Nano Banana Pro maps to gemini-3-pro-image-preview
  const ai = getAI();
  
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Data,
            mimeType: mimeType,
          },
        },
        {
          text: PROMPT_MICHELIN + " Ensure hyper-realistic textures and award-winning culinary aesthetics.",
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1",
        imageSize: "1K"
      }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  throw new Error("No image generated by Nano Banana Pro");
};

export const generatePlatingGuide = async (base64Input: string): Promise<string> => {
  // Use Gemini 3 Pro for complex layout instruction (2x2 grid)
  const ai = getAI();
  
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Input,
            mimeType: 'image/png', // Assuming input is PNG from previous gen, or match source
          },
        },
        {
          text: PROMPT_GUIDE,
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1",
        imageSize: "1K"
      }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  throw new Error("Failed to generate plating guide");
};